"""Generate scalar and fixed-layout resource ABI forwarding; locks stay explicit."""
import pathlib
import re
import sys
header = pathlib.Path(sys.argv[1]).read_text()
interfaces = [
    (3, "IDirect3DTexture9", {17,18,19,20}), (4, "IDirect3DCubeTexture9", {17,18,19,20}),
    (5, "IDirect3DSurface9", {11,12,13,14,15,16}), (6, "IDirect3DVertexBuffer9", {11,12}),
    (7, "IDirect3DIndexBuffer9", {11,12}), (8, "IDirect3DVertexShader9", set()),
    (9, "IDirect3DPixelShader9", set()), (10, "IDirect3DVertexDeclaration9", set()),
    (11, "IDirect3DStateBlock9", set()), (12, "IDirect3DQuery9", set()),
    (13, "IDirect3DSwapChain9", {9}), (14, "IDirect3DVolumeTexture9", {18,19,20}),
    (15, "IDirect3DVolume9", {7,9,10}),
]
output = ["// Generated by ports/dxvk_android/generate_resource_bridge.py.\n"]
for kind, interface, omitted in interfaces:
    start = re.search(r"DECLARE_INTERFACE_\("+interface+r",\s*\w+\)", header).start()
    body = header[start:header.index("};", start)]
    methods = re.findall(r"STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\s*\((.*?)\)\s*PURE", body, re.S)
    output.append(f"if(kind=={kind}){{auto resource=static_cast<{interface}*>(object);switch(method){{\n")
    for slot, (result, name, ordinary, parameters) in enumerate(methods):
        if slot < 3 or slot in omitted:
            continue
        name = name or ordinary;result = result or "HRESULT"
        parameters = re.sub(r"\s+", " ", parameters).strip()
        parameters = parameters.removeprefix("THIS_").strip() if parameters != "THIS" else ""
        parameters = parameters.split(",") if parameters else []
        call, setup, complete = [], [], []
        for index, parameter in enumerate(parameters, 1):
            type_name = re.sub(r"(\*|\s)([A-Za-z_]\w*)$", r"\1", parameter.strip()).strip()
            type_name = re.sub(r"\s*\*\s*", "*", type_name);argument=f"args[{index}]"
            if type_name.startswith("struct "):type_name=type_name[7:]
            if type_name.endswith("**"):
                base = type_name[:-2]
                kind_name = {"IDirect3DDevice9":"Device", "IDirect3DSurface9":"Surface"}.get(base)
                if not kind_name:raise ValueError(type_name)
                setup.append(f"{base}* result{index}=nullptr;")
                call.append(f"{argument}?&result{index}:nullptr")
                complete.append(f"if({argument})write({argument},SUCCEEDED(status)?wrap(result{index},Kind::{kind_name}):0);")
            elif type_name.startswith("IDirect3D") and type_name.endswith("*"):
                call.append(f"nativeObject<{type_name[:-1]}>({argument})")
            elif type_name in ("REFGUID","REFIID"):
                call.append(f"*static_cast<const GUID*>(pointer({argument}))")
            elif type_name == "HWND":call.append(f"{argument}?hostWindow.load():nullptr")
            elif "*" in type_name:call.append(f"static_cast<{type_name}>(pointer({argument}))")
            else:call.append(f"static_cast<{type_name}>({argument})")
        if name == "SetPrivateData":setup.append('if(args[4]&1)throw std::runtime_error("COM private IUnknown data pending");')
        output.append(f"case {slot}:{{*argumentCount={len(parameters)+1};"+"".join(setup))
        invocation=f"resource->{name}({','.join(call)})"
        if complete:output.append(f"HRESULT status={invocation};"+"".join(complete)+"return status;}")
        elif result=="void":output.append(invocation+";return 0;}")
        else:output.append("return "+invocation+";}")
        output.append("\n")
    output.append("}}\n")
pathlib.Path(sys.argv[2]).write_text("".join(output))
print("Generated resource methods for", len(interfaces), "COM types")
