"""Emit explicit x86-stack to native D3D9 device calls from the pinned ABI."""
import pathlib
import re
import sys
header = pathlib.Path(sys.argv[1]).read_text()
start = header.index("DECLARE_INTERFACE_(IDirect3DDevice9,IUnknown)")
interface = header[start:header.index("};", start)]
methods = re.findall(r"STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\s*\((.*?)\)\s*PURE", interface, re.S)
assert len(methods) == 119 and methods[43][2] == "Clear"
kinds = {"IDirect3D9": "D3D9", "IDirect3DDevice9": "Device", "IDirect3DTexture9": "Texture",
         "IDirect3DCubeTexture9": "Cube", "IDirect3DSurface9": "Surface", "IDirect3DVertexBuffer9": "VertexBuffer",
         "IDirect3DIndexBuffer9": "IndexBuffer", "IDirect3DVertexShader9": "VertexShader", "IDirect3DPixelShader9": "PixelShader",
         "IDirect3DVertexDeclaration9": "Declaration", "IDirect3DStateBlock9": "StateBlock", "IDirect3DQuery9": "Query",
         "IDirect3DSwapChain9": "SwapChain", "IDirect3DVolumeTexture9": "VolumeTexture"}
output = ["// Generated by ports/dxvk_android/generate_device_bridge.py.\n"]
for slot, (result, name, ordinary, parameters) in enumerate(methods):
    name = name or ordinary
    result = result or "HRESULT"
    if slot in (0, 1, 2, 9, 13, 16, 23, 25):
        continue
    parameters = re.sub(r"\s+", " ", parameters).strip()
    parameters = parameters.removeprefix("THIS_").strip() if parameters != "THIS" else ""
    parameters = parameters.split(",") if parameters else []
    call, setup, complete = [], [], []
    for index, parameter in enumerate(parameters, 1):
        type_name = re.sub(r"(\*|\s)([A-Za-z_]\w*)$", r"\1", parameter.strip()).strip()
        type_name = re.sub(r"\s*\*\s*", "*", type_name)
        argument = f"args[{index}]"
        if type_name.endswith("**") and type_name[:-2].startswith("IDirect3D"):
            base = type_name[:-2]
            setup.append(f"{base}* object{index}=nullptr;")
            call.append(f"{argument}?&object{index}:nullptr")
            wrapped = f"wrapTexture(object{index})" if base == "IDirect3DBaseTexture9" else f"wrap(object{index},Kind::{kinds[base]})"
            complete.append(f"if({argument})write({argument},SUCCEEDED(status)?{wrapped}:0);")
        elif type_name.startswith("IDirect3D") and type_name.endswith("*"):
            call.append(f"nativeObject<{type_name[:-1]}>({argument})")
        elif type_name == "HANDLE*":
            setup.append(f'if({argument})throw std::runtime_error("D3D9 shared resource handles pending");')
            call.append("nullptr")
        elif type_name == "HWND":
            call.append(f"{argument}?hostWindow.load():nullptr")
        elif "*" in type_name:
            call.append(f"static_cast<{type_name}>(pointer({argument}))")
        elif type_name == "float":
            call.append(f"floatValue({argument})")
        else:
            call.append(f"static_cast<{type_name}>({argument})")
    output.append(f"case {slot}:{{*argumentCount={len(parameters)+1};" + "".join(setup))
    invocation = f"device->{name}({','.join(call)})"
    if complete:
        output.append(f"HRESULT status={invocation};" + "".join(complete) + "return status;}")
    elif result == "void":
        output.append(invocation + ";return 0;}")
    elif result == "float":
        output.append(f"return floatBits({invocation});}}")
    else:
        output.append(f"return {invocation};}}")
    output.append("\n")
pathlib.Path(sys.argv[2]).write_text("".join(output))
print("Emitted", len(methods)-8, "device ABI methods")
